/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f446xx.h>
#include <common.h>
#include <port_init.h>
#include <timer_init.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Function Prototype
 */
void init(void);



int main(void)
{
  UINT16 COUNT = 0;

  init();

  while(1){

    //Polling for user button press
    while((GPIOC->IDR & (1U << 13))){}

    //Onboard LED ON, cycle is in process.
    GPIOA_BSRR_SEL(PIN_5, BSRR_PIN_SET);

    /*
     *  Code responsible for turning on the LED and charging the TIA
     */

    GPIOA_BSRR_SEL(PIN_6, BSRR_PIN_SET);  //Turn on IR LED
    LCD_DELAY_OPM_TIMER_UPDATE(10); //Delay to ensure LED is properly turned on
    while(!(TIM2_COMPLETE_EVENT)){}
    
    for(COUNT = 0; COUNT < 100; COUNT++){

      GPIOA_BSRR_SEL(PIN_7, BSRR_PIN_SET);  //Start charging TIA
      LCD_DELAY_OPM_TIMER_UPDATE(10); //Delay to ensure TIA is charged to 1ms
      while(!(TIM2_COMPLETE_EVENT)){}

      GPIOA_BSRR_SEL(PIN_7, BSRR_PIN_CLEAR);  //Resets TIA
      LCD_DELAY_OPM_TIMER_UPDATE(10); //Delay between different TIA charging cycles
      while(!(TIM2_COMPLETE_EVENT)){}
    }

    GPIOA_BSRR_SEL(PIN_6, BSRR_PIN_CLEAR);  //Turn off IR LED

    LCD_DELAY_OPM_TIMER_UPDATE(10000);
    while(!(TIM2_COMPLETE_EVENT)){}

    //Onboard LED OFF, cycle is finished.
    GPIOA_BSRR_SEL(PIN_5, BSRR_PIN_CLEAR);
  }
}

void init(void){
  
  //Configuring Blue Push-Button
  RCC_GPIO_CLK_ENABLE(GPIOC_CLK_EN);
  GPIOC_MODER_SEL(PIN_13, INPUT_SEL);

  //Configuring onboard LED for testing
  RCC_GPIO_CLK_ENABLE(GPIOA_CLK_EN);
  GPIOA_MODER_SEL(PIN_5, OUTPUT_SEL);

  //Configuring GPIO pin to drive LED
  GPIOA_MODER_SEL(PIN_6, OUTPUT_SEL);

  //Configuring GPIO pin to drive TIA
  GPIOA_MODER_SEL(PIN_7, OUTPUT_SEL);

  //Initializing One Pulse Mode Timer for 1ms
  LCD_DELAY_OPM_TIMER_INIT(10);
  while(!(TIM2_COMPLETE_EVENT)){}
}
